#!/bin/zsh

# from https://qiita.com/matsubo/items/50a2530e6d6f9ac0645e

TARGETUSER=$1

echo -n "Input ${TARGETUSER}'s password > "
read  -s PASSWORD

GID=`dscl . list groups gid|grep \^staff | tail  -1  | awk '{print $2}'`

dscl . -create /Users/$TARGETUSER
dscl . -create /Users/$TARGETUSER UserShell /bin/bash
dscl . -create /Users/$TARGETUSER RealName $TARGETUSER

maxid=$(dscl . -list /Users UniqueID | awk '{print $2}' | sort -ug | tail -1)
newid=$((maxid+1))

dscl . -create /Users/$TARGETUSER UniqueID         $newid
dscl . -create /Users/$TARGETUSER PrimaryGroupID   $GID
dscl . -create /Users/$TARGETUSER NFSHomeDirectory /Users/$TARGETUSER

cp -a /System/Library/User\ Template/English.lproj /Users/$TARGETUSER
chown -R $TARGETUSER\:staff /Users/$TARGETUSER
chmod 701 /Users/$TARGETUSER
dscl . -passwd /Users/$TARGETUSER $PASSWORD
